use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

use rust_i18n::t;

/// Snapshot of a single session at a point in time.
/// This is the unified data model all providers produce.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SessionSnapshot {
    pub session_id: String,
    pub provider: String,
    pub model: String,
    pub input_tokens: u64,
    pub output_tokens: u64,
    pub cache_creation_tokens: u64,
    pub cache_read_tokens: u64,
    pub context_tokens: Option<u64>, // current tokens in context window
    pub context_max: Option<u64>,    // context window capacity
    pub context_window_pct: Option<f64>,
    pub input_tps: Option<f64>,  // input tokens per second
    pub output_tps: Option<f64>, // output tokens per second
    pub cost_reported: Option<f64>,
    pub git_branch: Option<String>,
    pub work_dir: Option<String>,
    pub status: SessionStatus,
    pub timestamp: DateTime<Utc>,
    /// Number of currently active subagents (mtime < 5min)
    pub active_subagents: usize,
    /// Total number of subagent JSONL files in this session
    pub total_subagents: usize,
}

impl SessionSnapshot {
    /// Merge another snapshot into self. The incoming snapshot updates
    /// cumulative counters (always picks the higher value) and fills in
    /// `Option` fields only when the new value is `Some` — this prevents
    /// a less-rich source (e.g. JSONL logs) from wiping out richer data
    /// (e.g. statusline with context_pct / cost / tps).
    pub fn merge(&mut self, other: &SessionSnapshot) {
        // Always take the newer timestamp
        if other.timestamp > self.timestamp {
            self.timestamp = other.timestamp;
            self.status = other.status;
        }

        // Cumulative counters: pick whichever is larger
        self.input_tokens = self.input_tokens.max(other.input_tokens);
        self.output_tokens = self.output_tokens.max(other.output_tokens);
        self.cache_creation_tokens = self.cache_creation_tokens.max(other.cache_creation_tokens);
        self.cache_read_tokens = self.cache_read_tokens.max(other.cache_read_tokens);

        // Model: prefer non-empty
        if !other.model.is_empty() {
            self.model.clone_from(&other.model);
        }

        // Optional fields: incoming Some overwrites, None preserves existing
        if other.context_tokens.is_some() {
            self.context_tokens = other.context_tokens;
        }
        if other.context_max.is_some() {
            self.context_max = other.context_max;
        }
        if other.context_window_pct.is_some() {
            self.context_window_pct = other.context_window_pct;
        }
        if other.input_tps.is_some() {
            self.input_tps = other.input_tps;
        }
        if other.output_tps.is_some() {
            self.output_tps = other.output_tps;
        }
        if other.cost_reported.is_some() {
            self.cost_reported = other.cost_reported;
        }
        if other.git_branch.is_some() {
            self.git_branch.clone_from(&other.git_branch);
        }
        if other.work_dir.is_some() {
            self.work_dir.clone_from(&other.work_dir);
        }
        self.active_subagents = other.active_subagents;
        self.total_subagents = self.total_subagents.max(other.total_subagents);
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum SessionStatus {
    Active,
    Idle,
    Done,
    Disconnected,
}

impl std::fmt::Display for SessionStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Active => write!(f, "{}", t!("status.active")),
            Self::Idle => write!(f, "{}", t!("status.idle")),
            Self::Done => write!(f, "{}", t!("status.done")),
            Self::Disconnected => write!(f, "{}", t!("status.disconnected")),
        }
    }
}

/// Alerts generated by the alert engine.
#[derive(Debug, Clone)]
pub enum Alert {
    ContextHigh {
        session_id: String,
        provider: String,
        pct: f64,
    },
    CostThreshold {
        session_id: String,
        cost: f64,
        threshold: f64,
    },
    ProviderDisconnected {
        provider: String,
        error: Option<String>,
    },
}

impl std::fmt::Display for Alert {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ContextHigh {
                session_id,
                provider,
                pct,
            } => {
                write!(
                    f,
                    "{}",
                    t!(
                        "alert.context_high",
                        provider = provider,
                        session_id = &session_id[..session_id.len().min(6)],
                        pct = format!("{pct:.0}")
                    )
                )
            }
            Self::CostThreshold {
                session_id,
                cost,
                threshold,
            } => {
                write!(
                    f,
                    "{}",
                    t!(
                        "alert.cost_threshold",
                        session_id = &session_id[..session_id.len().min(6)],
                        cost = format!("{cost:.2}"),
                        threshold = format!("{threshold:.2}")
                    )
                )
            }
            Self::ProviderDisconnected { provider, error } => {
                let msg = error.as_deref().unwrap_or("unknown");
                write!(
                    f,
                    "{}",
                    t!(
                        "alert.provider_disconnected",
                        provider = provider,
                        error = msg
                    )
                )
            }
        }
    }
}
