use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// Snapshot of a single session at a point in time.
/// This is the unified data model all providers produce.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SessionSnapshot {
    pub session_id: String,
    pub provider: String,
    pub model: String,
    pub input_tokens: u64,
    pub output_tokens: u64,
    pub cache_creation_tokens: u64,
    pub cache_read_tokens: u64,
    pub context_tokens: Option<u64>, // current tokens in context window
    pub context_max: Option<u64>,    // context window capacity
    pub context_window_pct: Option<f64>,
    pub input_tps: Option<f64>,  // input tokens per second
    pub output_tps: Option<f64>, // output tokens per second
    pub cost_reported: Option<f64>,
    pub git_branch: Option<String>,
    pub work_dir: Option<String>,
    pub status: SessionStatus,
    pub timestamp: DateTime<Utc>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum SessionStatus {
    Active,
    Idle,
    Done,
    Disconnected,
}

impl std::fmt::Display for SessionStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Active => write!(f, "Active"),
            Self::Idle => write!(f, "Idle"),
            Self::Done => write!(f, "Done"),
            Self::Disconnected => write!(f, "Disconnected"),
        }
    }
}

/// Alerts generated by the alert engine.
#[derive(Debug, Clone)]
pub enum Alert {
    ContextHigh {
        session_id: String,
        provider: String,
        pct: f64,
    },
    CostThreshold {
        session_id: String,
        cost: f64,
        threshold: f64,
    },
    ProviderDisconnected {
        provider: String,
        error: Option<String>,
    },
}

impl std::fmt::Display for Alert {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ContextHigh {
                session_id,
                provider,
                pct,
            } => {
                write!(f, "{provider}#{session_id} context {pct:.0}%")
            }
            Self::CostThreshold {
                session_id,
                cost,
                threshold,
            } => {
                write!(f, "#{session_id} cost ${cost:.2} exceeds ${threshold:.2}")
            }
            Self::ProviderDisconnected { provider, error } => {
                let msg = error.as_deref().unwrap_or("unknown");
                write!(f, "{provider} disconnected: {msg}")
            }
        }
    }
}
