use std::fs;
use std::path::PathBuf;

/// The bridge script wraps any existing statusline command.
/// It reads JSON from stdin, forwards to tokemon socket, then pipes
/// the same JSON to the original command (if configured).
const STATUSLINE_SCRIPT: &str = r##"#!/bin/bash
# tokemon statusline bridge — auto-generated by `tokemon setup claude-code`
# Wraps the original statusline command and forwards data to tokemon.
#
# To use a custom statusline command (e.g. ccstatusline), set:
#   TOKEMON_ORIGINAL_CMD="ccstatusline"
# in this file, or pass it as an env var.

SOCKET="${TMPDIR:-/tmp}tokemon-claude.sock"

# Original statusline command to wrap (leave empty for tokemon-only output)
TOKEMON_ORIGINAL_CMD="${TOKEMON_ORIGINAL_CMD:-__ORIGINAL_CMD__}"

# Read JSON from stdin
data=$(cat)

# Forward to tokemon socket (non-blocking, silent if tokemon isn't running)
if [ -S "$SOCKET" ]; then
    echo "$data" | jq -c . 2>/dev/null | nc -U -w0 "$SOCKET" 2>/dev/null &
fi

# If we have an original command, pipe data to it and use its output
if [ -n "$TOKEMON_ORIGINAL_CMD" ] && command -v "$TOKEMON_ORIGINAL_CMD" >/dev/null 2>&1; then
    echo "$data" | "$TOKEMON_ORIGINAL_CMD"
    exit $?
fi

# Fallback: simple status line output
model=$(echo "$data" | jq -r '.model.display_name // "?"')
ctx_pct=$(echo "$data" | jq -r '.context_window.used_percentage // 0' | xargs printf '%.0f')
cost=$(echo "$data" | jq -r '.cost.total_cost_usd // 0' | xargs printf '%.2f')

echo "${model} | ctx ${ctx_pct}% | \$${cost}"
"##;

pub fn run(provider: &str) -> anyhow::Result<()> {
    match provider.to_lowercase().replace(' ', "-").as_str() {
        "claude-code" | "claudecode" | "cc" => setup_claude_code(),
        "codebuddy" | "code-buddy" | "cb" => setup_codebuddy(),
        other => {
            eprintln!("Unknown provider: {other}");
            eprintln!("Available providers: claude-code, codebuddy");
            std::process::exit(1);
        }
    }
}

fn setup_claude_code() -> anyhow::Result<()> {
    let home = dirs::home_dir().expect("Cannot determine home directory");
    let claude_dir = home.join(".claude");
    fs::create_dir_all(&claude_dir)?;

    let script_path = claude_dir.join("statusline.sh");

    // Detect existing statusline setup
    let original_cmd = detect_original_command(&claude_dir);

    // Backup existing script if it wasn't ours
    if script_path.exists() {
        let content = fs::read_to_string(&script_path).unwrap_or_default();
        if !content.contains("tokemon statusline bridge") {
            let backup = claude_dir.join("statusline.sh.bak");
            fs::copy(&script_path, &backup)?;
            println!("  ✓ Backed up original → {}", backup.display());
        }
    }

    // Write script, filling in original command
    let script = STATUSLINE_SCRIPT.replace("__ORIGINAL_CMD__", &original_cmd);
    fs::write(&script_path, script)?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(&script_path, fs::Permissions::from_mode(0o755))?;
    }

    println!("  ✓ Wrote {}", script_path.display());
    if !original_cmd.is_empty() {
        println!("  ✓ Wrapping original command: {original_cmd}");
    }

    // Update settings.json
    let settings_path = claude_dir.join("settings.json");
    let updated = update_settings(&settings_path)?;
    if updated {
        println!("  ✓ Updated {}", settings_path.display());
    } else {
        println!("  ✓ {} already configured", settings_path.display());
    }

    println!();
    println!("  Setup complete! Restart Claude Code for changes to take effect.");
    println!();
    println!("  Then run:");
    println!("    tokemon");
    println!();

    Ok(())
}

/// Try to detect what statusline command was previously configured.
fn detect_original_command(claude_dir: &std::path::Path) -> String {
    let settings_path = claude_dir.join("settings.json");
    if !settings_path.exists() {
        return String::new();
    }

    let content = fs::read_to_string(&settings_path).unwrap_or_default();
    let settings: serde_json::Value = serde_json::from_str(&content).unwrap_or_default();

    if let Some(cmd) = settings
        .get("statusLine")
        .and_then(|sl| sl.get("command"))
        .and_then(|c| c.as_str())
    {
        // If it's already our script, look for the backup or known tools
        if cmd.contains("statusline.sh") {
            // Check if there's a known tool installed
            for tool in &["ccstatusline", "ccometixline", "claude-powerline"] {
                if which_exists(tool) {
                    return tool.to_string();
                }
            }
            return String::new();
        }
        // It's pointing to some other command — preserve it
        return cmd.to_string();
    }

    String::new()
}

fn which_exists(cmd: &str) -> bool {
    std::process::Command::new("which")
        .arg(cmd)
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

fn update_settings(path: &PathBuf) -> anyhow::Result<bool> {
    let mut settings: serde_json::Value = if path.exists() {
        let content = fs::read_to_string(path)?;
        serde_json::from_str(&content).unwrap_or_else(|_| serde_json::json!({}))
    } else {
        serde_json::json!({})
    };

    if settings.get("statusLine").is_some() {
        let existing = settings["statusLine"]["command"].as_str().unwrap_or("");
        if existing.contains("statusline.sh") {
            return Ok(false);
        }
    }

    settings["statusLine"] = serde_json::json!({
        "type": "command",
        "command": "~/.claude/statusline.sh"
    });

    let formatted = serde_json::to_string_pretty(&settings)?;
    fs::write(path, formatted)?;

    Ok(true)
}

// ============================================================
// CodeBuddy setup
// ============================================================

/// The CodeBuddy bridge script. It reads JSON from stdin, forwards to the
/// tokemon socket, then pipes the same data to the original statusline command.
const CODEBUDDY_BRIDGE_SCRIPT: &str = r##"#!/bin/bash
# tokemon statusline bridge for CodeBuddy — auto-generated by `tokemon setup codebuddy`
# Wraps the original statusline command and forwards data to tokemon.

SOCKET="${TMPDIR:-/tmp}tokemon-codebuddy.sock"

# Original statusline command to chain (leave empty for tokemon-only output)
TOKEMON_ORIGINAL_CMD="__ORIGINAL_CMD__"

# Read JSON from stdin
data=$(cat)

# Forward to tokemon socket (non-blocking, silent if tokemon isn't running)
if [ -S "$SOCKET" ]; then
    echo "$data" | jq -c . 2>/dev/null | nc -U -w0 "$SOCKET" 2>/dev/null &
fi

# If we have an original command, pipe data to it and use its output
if [ -n "$TOKEMON_ORIGINAL_CMD" ] && [ -x "$TOKEMON_ORIGINAL_CMD" ]; then
    echo "$data" | "$TOKEMON_ORIGINAL_CMD"
    exit $?
elif [ -n "$TOKEMON_ORIGINAL_CMD" ]; then
    echo "$data" | /bin/bash "$TOKEMON_ORIGINAL_CMD"
    exit $?
fi

# Fallback: simple status line output
model=$(echo "$data" | jq -r '.model.display_name // .model.id // "?"')
ctx_pct=$(echo "$data" | jq -r '.context_window.used_percentage // 0' | xargs printf '%.0f')
echo "${model} | ctx ${ctx_pct}%"
"##;

fn setup_codebuddy() -> anyhow::Result<()> {
    let home = dirs::home_dir().expect("Cannot determine home directory");
    let codebuddy_dir = home.join(".codebuddy");
    fs::create_dir_all(&codebuddy_dir)?;

    let bridge_path = codebuddy_dir.join("tokemon-statusline.sh");

    // Detect existing statusline command to chain
    let original_cmd = detect_codebuddy_original_command(&codebuddy_dir);

    // Write bridge script
    let script = CODEBUDDY_BRIDGE_SCRIPT.replace("__ORIGINAL_CMD__", &original_cmd);
    fs::write(&bridge_path, script)?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(&bridge_path, fs::Permissions::from_mode(0o755))?;
    }

    println!("  ✓ Wrote {}", bridge_path.display());
    if !original_cmd.is_empty() {
        println!("  ✓ Chaining to original: {original_cmd}");
    }

    // Update settings.json
    let settings_path = codebuddy_dir.join("settings.json");
    let updated = update_codebuddy_settings(&settings_path, &bridge_path)?;
    if updated {
        println!("  ✓ Updated {}", settings_path.display());
    } else {
        println!("  ✓ {} already configured", settings_path.display());
    }

    println!();
    println!("  Setup complete! Restart CodeBuddy for changes to take effect.");
    println!();
    println!("  Then run:");
    println!("    tokemon");
    println!();

    Ok(())
}

/// Detect existing statusline command from CodeBuddy settings.
fn detect_codebuddy_original_command(codebuddy_dir: &std::path::Path) -> String {
    let settings_path = codebuddy_dir.join("settings.json");
    if !settings_path.exists() {
        return String::new();
    }

    let content = fs::read_to_string(&settings_path).unwrap_or_default();
    let settings: serde_json::Value = serde_json::from_str(&content).unwrap_or_default();

    if let Some(cmd) = settings
        .get("statusLine")
        .and_then(|sl| sl.get("command"))
        .and_then(|c| c.as_str())
    {
        // If it's already our bridge, don't nest
        if cmd.contains("tokemon-statusline") {
            return String::new();
        }
        // Extract the actual command (may be "/bin/bash /path/to/script.sh")
        let cmd_str = cmd.to_string();
        // Strip leading "/bin/bash " if present
        let cleaned = cmd_str
            .strip_prefix("/bin/bash ")
            .unwrap_or(&cmd_str)
            .to_string();
        return cleaned;
    }

    String::new()
}

fn update_codebuddy_settings(
    path: &PathBuf,
    bridge_path: &std::path::Path,
) -> anyhow::Result<bool> {
    let mut settings: serde_json::Value = if path.exists() {
        let content = fs::read_to_string(path)?;
        serde_json::from_str(&content).unwrap_or_else(|_| serde_json::json!({}))
    } else {
        serde_json::json!({})
    };

    // Check if already pointing to our bridge
    if settings
        .get("statusLine")
        .and_then(|sl| sl.get("command"))
        .and_then(|c| c.as_str())
        .is_some_and(|cmd| cmd.contains("tokemon-statusline"))
    {
        return Ok(false);
    }

    let bridge_cmd = format!("/bin/bash {}", bridge_path.display());
    settings["statusLine"] = serde_json::json!({
        "type": "command",
        "command": bridge_cmd
    });

    let formatted = serde_json::to_string_pretty(&settings)?;
    fs::write(path, formatted)?;

    Ok(true)
}
